#!/usr/bin/env bash

#fix container:: task2
pkill -f apache2
chmod 644 /etc/nginx.conf
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
